version: '3'

services:
  back_serv:
    container_name: hello_ubuntu
    image: hello_ubuntu:21.10
    networks:
      - S21_net
  
    
  proxy_serv:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    networks:
      - S21_net

networks:
  S21_net:
    driver: bridge


  




